/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    AssetManagerPanel: typeof import('./src/components/AssetManagerPanel.vue')['default']
    BarChart: typeof import('./../slidev/components/block/BarChart.vue')['default']
    BeitouBackCover: typeof import('./../slidev/layouts/beitou/beitou-back-cover.vue')['default']
    BeitouContent: typeof import('./../slidev/layouts/beitou/beitou-content.vue')['default']
    BeitouCover: typeof import('./../slidev/layouts/beitou/beitou-cover.vue')['default']
    BeitouImageContent: typeof import('./../slidev/layouts/beitou/beitou-image-content.vue')['default']
    BeitouSectionTitle: typeof import('./../slidev/layouts/beitou/beitou-section-title.vue')['default']
    BeitouToc: typeof import('./../slidev/layouts/beitou/beitou-toc.vue')['default']
    ChatPanel: typeof import('./src/components/ChatPanel.vue')['default']
    DeckEditorCanvas: typeof import('./src/components/DeckEditorCanvas.vue')['default']
    EqualSplit: typeof import('./../slidev/components/grid/EqualSplit.vue')['default']
    ExportModal: typeof import('./src/components/ExportModal.vue')['default']
    ExportRenderer: typeof import('./src/components/ExportRenderer.vue')['default']
    ImageJobsPanel: typeof import('./src/components/ImageJobsPanel.vue')['default']
    ImageStyleCard: typeof import('./src/components/ImageStyleCard.vue')['default']
    ImageStyleLibraryModal: typeof import('./src/components/ImageStyleLibraryModal.vue')['default']
    ImageText: typeof import('./../slidev/components/grid/ImageText.vue')['default']
    JingyedaBackCover: typeof import('./../slidev/layouts/jingyeda/jingyeda-back-cover.vue')['default']
    JingyedaContent: typeof import('./../slidev/layouts/jingyeda/jingyeda-content.vue')['default']
    JingyedaCover: typeof import('./../slidev/layouts/jingyeda/jingyeda-cover.vue')['default']
    JingyedaImageContent: typeof import('./../slidev/layouts/jingyeda/jingyeda-image-content.vue')['default']
    JingyedaSectionTitle: typeof import('./../slidev/layouts/jingyeda/jingyeda-section-title.vue')['default']
    JingyedaToc: typeof import('./../slidev/layouts/jingyeda/jingyeda-toc.vue')['default']
    LBeitouCoverLogo: typeof import('./../slidev/components/private/LBeitouCoverLogo.vue')['default']
    LBeitouTitleBlock: typeof import('./../slidev/components/private/LBeitouTitleBlock.vue')['default']
    LBtHeader: typeof import('./../slidev/components/private/LBtHeader.vue')['default']
    LineChart: typeof import('./../slidev/components/block/LineChart.vue')['default']
    LJydHeader: typeof import('./../slidev/components/private/LJydHeader.vue')['default']
    MCPCatalogItem: typeof import('./src/components/MCPCatalogItem.vue')['default']
    MCPCustomServer: typeof import('./src/components/MCPCustomServer.vue')['default']
    MetricCard: typeof import('./../slidev/components/block/MetricCard.vue')['default']
    NineGrid: typeof import('./../slidev/components/grid/NineGrid.vue')['default']
    OneVsThree: typeof import('./../slidev/components/grid/OneVsThree.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    PetalFour: typeof import('./../slidev/components/decoration/PetalFour.vue')['default']
    PieChart: typeof import('./../slidev/components/block/PieChart.vue')['default']
    ProcessFlow: typeof import('./../slidev/components/decoration/ProcessFlow.vue')['default']
    Quote: typeof import('./../slidev/components/block/Quote.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    ShareModal: typeof import('./src/components/ShareModal.vue')['default']
    SixGrid: typeof import('./../slidev/components/grid/SixGrid.vue')['default']
    SlidePreview: typeof import('./src/components/SlidePreview.vue')['default']
    Table: typeof import('./../slidev/components/block/Table.vue')['default']
    TemplateCard: typeof import('./src/components/TemplateCard.vue')['default']
    TemplatePickerModal: typeof import('./src/components/TemplatePickerModal.vue')['default']
    TemplatePreviewPane: typeof import('./src/components/TemplatePreviewPane.vue')['default']
    ThinkingBlock: typeof import('./src/components/ThinkingBlock.vue')['default']
    ToolExecutionBlock: typeof import('./src/components/ToolExecutionBlock.vue')['default']
    TwoColumnsTwoRows: typeof import('./../slidev/components/grid/TwoColumnsTwoRows.vue')['default']
    UndoToast: typeof import('./src/components/UndoToast.vue')['default']
    UploadButton: typeof import('./src/components/UploadButton.vue')['default']
    UploadProgress: typeof import('./src/components/UploadProgress.vue')['default']
    UsageStatsHint: typeof import('./src/components/UsageStatsHint.vue')['default']
    VersionTimeline: typeof import('./src/components/VersionTimeline.vue')['default']
  }
}
