// 预生成 Slidev UI 图标 CSS。
//
// 为什么要这么做：
//   UnoCSS 66.x 的 presetIcons 在 pnpm isolated monorepo 下
//   collectionsNodeResolvePath 自动解析彻底失效，Slidev 内部 i-carbon:*
//   等 class 都拿不到 SVG。用户 setup/unocss.ts 加的第二个 presetIcons
//   被忽略（preset 合并时同名被覆盖）。
//
// 解决：离线把 @slidev/client 里所有 i-carbon / i-ph / i-svg-spinners 类
//   扫出，用显式 async loader 的 presetIcons 生成 CSS，写到
//   packages/slidev/styles/icons.css，再由项目级 style.css @import 注入。
//
// 何时重跑：
//   - Slidev 大版本升级后（@slidev/client 内可能新增图标引用）
//   - 定制 NavControls / 加 addon 引入新图标时
//
// 命令：pnpm --filter @big-ppt/slidev run gen-icons

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { execSync } from 'node:child_process'
import { createGenerator } from 'unocss'
import { presetIcons } from '@unocss/preset-icons'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const PKG_ROOT = path.resolve(__dirname, '..')
const MONOREPO_ROOT = path.resolve(PKG_ROOT, '../..')

// 1. 定位 @slidev/client 源码目录（从 pnpm store）
const clientPath = execSync(
  `node -e "console.log(require.resolve('@slidev/client'))"`,
  { cwd: PKG_ROOT, encoding: 'utf-8' },
).trim()
const clientRoot = path.resolve(path.dirname(clientPath), '..')
console.log('[gen-icons] clientRoot:', clientRoot)

// 2. 扫所有 .vue / .ts 里 i-carbon / i-ph / i-svg-spinners 类
const classes = new Set()
function scan(dir) {
  if (!fs.existsSync(dir)) return
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) scan(full)
    else if (/\.(vue|ts|mjs|js)$/.test(entry.name)) {
      const src = fs.readFileSync(full, 'utf-8')
      for (const m of src.matchAll(/i-(carbon|ph|svg-spinners)[:-][a-z0-9-]+/g)) {
        classes.add(m[0])
      }
    }
  }
}
scan(clientRoot)
console.log('[gen-icons] detected classes:', classes.size)

// 3. 用显式 async loader 生成 CSS
const uno = await createGenerator({
  presets: [
    presetIcons({
      warn: true,
      collections: {
        carbon: () =>
          import('@iconify-json/carbon/icons.json', { with: { type: 'json' } }).then(
            (m) => m.default,
          ),
        ph: () =>
          import('@iconify-json/ph/icons.json', { with: { type: 'json' } }).then((m) => m.default),
        'svg-spinners': () =>
          import('@iconify-json/svg-spinners/icons.json', { with: { type: 'json' } }).then(
            (m) => m.default,
          ),
      },
    }),
  ],
})

const sorted = [...classes].sort()
const result = await uno.generate(sorted.join(' '), { preflights: false, minify: true })
console.log('[gen-icons] matched:', result.matched.size, '/', sorted.length)
if (result.matched.size < sorted.length) {
  const missed = sorted.filter((c) => !result.matched.has(c))
  console.warn('[gen-icons] unmatched classes:', missed.join(', '))
}

// 4. 写入
const outDir = path.join(PKG_ROOT, 'styles')
fs.mkdirSync(outDir, { recursive: true })
const outPath = path.join(outDir, 'icons.css')
const header = `/* auto-generated by scripts/gen-icons.mjs — ${new Date().toISOString()} */\n`
fs.writeFileSync(outPath, header + result.css + '\n')
console.log('[gen-icons] wrote', path.relative(MONOREPO_ROOT, outPath), '(', result.css.length, 'B )')
